harnessApiVersion: '1.0'
type: SETUP
commandUnitType: COMMAND
commandUnits:
- command: |-
    curl -L https://raw.githubusercontent.com/gabrielcerioni/harness_prometheus/main/prom_configs/prometheus.yml -o /etc/prometheus/prometheus.yml

    echo "Printing the file content:"
    echo ""

    cat /etc/prometheus/prometheus.yml
  commandUnitType: EXEC
  deploymentType: SSH
  name: Copy the latest Prometheus Config
  scriptType: BASH
  workingDirectory: /tmp
- command: |
    curl -i -X POST http://localhost:9090/-/reload
  commandUnitType: EXEC
  deploymentType: SSH
  name: Reload Prometheus
  scriptType: BASH
  workingDirectory: /tmp
targetToAllEnv: true
