harnessApiVersion: '1.0'
type: SETUP
commandUnitType: COMMAND
commandUnits:
- command: |
    curl -i -X POST http://localhost:9090/-/reload
  commandUnitType: EXEC
  deploymentType: SSH
  name: Exec
  scriptType: BASH
  workingDirectory: /tmp
targetToAllEnv: true
